-- ============================================================
-- 0008_fabricacion.sql
-- Pantalla de Fabricación: fabricaciones abiertas/cerradas con
-- baja de stock de insumos del taller.
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

-- La tabla del intento anterior de insumos en Taller ya no se usa.
drop table if exists public.taller_trabajo_insumos;

-- ------------------------------------------------------------
-- 1) Tablas
-- ------------------------------------------------------------
create table if not exists public.fabricaciones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cliente text,
  descripcion text,
  estado text not null default 'abierta' check (estado in ('abierta', 'cerrada')),
  fecha_apertura timestamptz not null default now(),
  fecha_cierre timestamptz,
  usuario_email text
);

create table if not exists public.fabricacion_insumos (
  id bigint generated by default as identity primary key,
  fabricacion_id bigint not null references public.fabricaciones(id) on delete cascade,
  insumo_id bigint not null references public.insumos(id),
  cantidad numeric not null default 1,
  fecha timestamptz not null default now(),
  usuario_email text
);

create index if not exists fabricacion_insumos_fabricacion_id_idx on public.fabricacion_insumos (fabricacion_id);
create index if not exists fabricaciones_estado_idx on public.fabricaciones (estado);

-- ------------------------------------------------------------
-- 2) RLS: solo admin (igual que Taller)
-- ------------------------------------------------------------
alter table public.fabricaciones enable row level security;
alter table public.fabricacion_insumos enable row level security;

drop policy if exists "fabricaciones_admin_all" on public.fabricaciones;
create policy "fabricaciones_admin_all" on public.fabricaciones
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());

drop policy if exists "fabricacion_insumos_admin_all" on public.fabricacion_insumos;
create policy "fabricacion_insumos_admin_all" on public.fabricacion_insumos
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());

-- ------------------------------------------------------------
-- 3) RPC: registrar movimiento de stock VINCULADO a una
--    fabricación abierta (opcional). Mantiene la firma anterior.
-- ------------------------------------------------------------
create or replace function public.registrar_movimiento_insumo(
  p_insumo_id bigint,
  p_tipo text,
  p_cantidad numeric,
  p_producto_texto text default null,
  p_nota text default null,
  p_usuario_email text default null,
  p_fabricacion_id bigint default null
)
returns table (ok boolean, mensaje text, nuevo_stock numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock numeric;
  v_nuevo numeric;
  v_unidad text;
  v_nombre text;
  v_rol text;
  v_estado text;
  v_obra text;
begin
  select rol into v_rol from public.perfiles where id = auth.uid();

  if v_rol is null then
    return query select false, 'Usuario sin rol asignado. Revisá la tabla perfiles.', null::numeric;
    return;
  end if;

  if p_tipo not in ('entrada', 'salida') then
    return query select false, 'Tipo de movimiento inválido.', null::numeric;
    return;
  end if;

  -- Solo el admin puede registrar entradas de stock
  if p_tipo = 'entrada' and v_rol <> 'admin' then
    return query select false, 'Solo el administrador puede registrar entradas.', null::numeric;
    return;
  end if;

  -- Las entradas no pueden vincularse a una fabricación
  if p_tipo = 'entrada' and p_fabricacion_id is not null then
    return query select false, 'Las entradas no se pueden vincular a una fabricación.', null::numeric;
    return;
  end if;

  -- Si viene vinculada a una fabricación: debe existir y estar abierta
  if p_fabricacion_id is not null then
    select estado, nombre into v_estado, v_obra
    from public.fabricaciones
    where id = p_fabricacion_id;

    if not found then
      return query select false, 'La fabricación no existe.', null::numeric;
      return;
    end if;

    if v_estado <> 'abierta' then
      return query select false, 'La fabricación ya está cerrada. No se pueden agregar más insumos.', null::numeric;
      return;
    end if;

    if p_producto_texto is null then
      p_producto_texto := v_obra;
    end if;
  end if;

  -- Bloquea la fila para evitar condiciones de carrera
  select stock, unidad, nombre into v_stock, v_unidad, v_nombre
  from public.insumos
  where id = p_insumo_id
  for update;

  if not found then
    return query select false, 'El insumo no existe.', null::numeric;
    return;
  end if;

  if p_tipo = 'entrada' then
    v_nuevo := v_stock + p_cantidad;
  else
    if p_cantidad > v_stock then
      return query select false, format('No hay suficiente stock: quedan %s %s de %s.', v_stock, v_unidad, v_nombre), null::numeric;
      return;
    end if;
    v_nuevo := v_stock - p_cantidad;
  end if;

  insert into public.movimientos (insumo_id, tipo, cantidad, producto_texto, nota, usuario_email, stock_resultante)
  values (p_insumo_id, p_tipo, p_cantidad, p_producto_texto, p_nota, p_usuario_email, v_nuevo);

  update public.insumos
  set stock = v_nuevo
  where id = p_insumo_id;

  -- Registra el consumo dentro de la fabricación abierta
  if p_fabricacion_id is not null then
    insert into public.fabricacion_insumos (fabricacion_id, insumo_id, cantidad, usuario_email)
    values (p_fabricacion_id, p_insumo_id, p_cantidad, p_usuario_email);
  end if;

  return query select true, 'Movimiento registrado.', v_nuevo;
end;
$$;

revoke all on function public.registrar_movimiento_insumo(bigint, text, numeric, text, text, text, bigint) from public;
grant execute on function public.registrar_movimiento_insumo(bigint, text, numeric, text, text, text, bigint) to authenticated;

-- ------------------------------------------------------------
-- 4) RPC: cerrar una fabricación abierta
-- ------------------------------------------------------------
create or replace function public.cerrar_fabricacion(p_fabricacion_id bigint)
returns table (ok boolean, mensaje text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rol text;
begin
  select rol into v_rol from public.perfiles where id = auth.uid();

  if v_rol is null or v_rol <> 'admin' then
    return query select false, 'Solo el administrador puede cerrar fabricaciones.';
    return;
  end if;

  update public.fabricaciones
  set estado = 'cerrada', fecha_cierre = now()
  where id = p_fabricacion_id and estado = 'abierta';

  if found then
    return query select true, 'Fabricación cerrada.';
  else
    return query select false, 'La fabricación no existe o ya está cerrada.';
  end if;
end;
$$;

revoke all on function public.cerrar_fabricacion(bigint) from public;
grant execute on function public.cerrar_fabricacion(bigint) to authenticated;
