-- ============================================================
-- 0010_fabricacion_estimados.sql
-- Estimativo de insumos a usar en cada fabricación (no afecta
-- el stock, es un plan).
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.fabricacion_estimados (
  id bigint generated by default as identity primary key,
  fabricacion_id bigint not null references public.fabricaciones(id) on delete cascade,
  insumo_id bigint not null references public.insumos(id),
  cantidad numeric not null default 1,
  fecha timestamptz not null default now(),
  usuario_email text
);

create index if not exists fabricacion_estimados_fabricacion_id_idx on public.fabricacion_estimados (fabricacion_id);

alter table public.fabricacion_estimados enable row level security;

drop policy if exists "fabricacion_estimados_admin_all" on public.fabricacion_estimados;
create policy "fabricacion_estimados_admin_all" on public.fabricacion_estimados
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());
