-- ============================================================
-- 0011_taller_items.sql
-- Trabajos anexados a cada trabajo de Taller: referencias a
-- trabajos de Corte Láser / Tornería, o ítems externos libres.
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.taller_trabajo_items (
  id bigint generated by default as identity primary key,
  taller_trabajo_id bigint not null references public.taller_trabajos(id) on delete cascade,
  tipo text not null check (tipo in ('trabajo', 'externo')),
  trabajo_ref bigint references public.trabajos(id),
  descripcion text,
  cantidad numeric,
  duracion_horas numeric,
  created_at timestamptz not null default now()
);

create index if not exists taller_trabajo_items_trabajo_idx on public.taller_trabajo_items (taller_trabajo_id);

alter table public.taller_trabajo_items enable row level security;

drop policy if exists "taller_trabajo_items_select_authenticated" on public.taller_trabajo_items;
create policy "taller_trabajo_items_select_authenticated" on public.taller_trabajo_items
  for select to authenticated using (true);

drop policy if exists "taller_trabajo_items_admin_write" on public.taller_trabajo_items;
create policy "taller_trabajo_items_admin_write" on public.taller_trabajo_items
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());
