-- ============================================================
-- 0013_precios_cotizaciones.sql
-- Catálogo de precios de materiales (por kg) y cotización de
-- obras de Fabricación (presupuesto + costeo).
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

-- ------------------------------------------------------------
-- 1) Catálogo de precios por insumo (tabla aparte del stock).
--    Cada material tiene peso por unidad (kg) y precio por kg.
--    Costo por unidad = peso_unitario_kg * precio_kg.
-- ------------------------------------------------------------
create table if not exists public.precios_materiales (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null unique references public.insumos(id) on delete cascade,
  peso_unitario_kg numeric not null default 0,
  precio_kg numeric not null default 0,
  usuario_email text,
  updated_at timestamptz not null default now()
);

create index if not exists precios_materiales_insumo_id_idx on public.precios_materiales (insumo_id);

alter table public.precios_materiales enable row level security;

drop policy if exists "precios_materiales_admin_all" on public.precios_materiales;
create policy "precios_materiales_admin_all" on public.precios_materiales
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());

-- ------------------------------------------------------------
-- 2) Cotizaciones de obras. Se guarda la configuración del
--    cálculo (valor hora, horas, margen, otros costos, estado);
--    los materiales se leen en vivo de fabricacion_estimados
--    (presupuesto) y fabricacion_insumos (costeo real).
-- ------------------------------------------------------------
create table if not exists public.cotizaciones (
  id bigint generated by default as identity primary key,
  fabricacion_id bigint not null unique references public.fabricaciones(id) on delete cascade,
  estado text not null default 'presupuesto' check (estado in ('presupuesto', 'aprobado', 'facturado')),
  valor_hora numeric not null default 0,
  horas numeric not null default 0,
  margen_porcentaje numeric not null default 0,
  otros_costos jsonb not null default '[]'::jsonb,
  usuario_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cotizaciones_fabricacion_id_idx on public.cotizaciones (fabricacion_id);

alter table public.cotizaciones enable row level security;

drop policy if exists "cotizaciones_admin_all" on public.cotizaciones;
create policy "cotizaciones_admin_all" on public.cotizaciones
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());
