-- ============================================================
-- 0015_articulos_externos.sql
-- Artículos externos por obra (ítems NO-stock con valor en $):
-- plegado tercerizado, soldadura externa, consumibles, etc.
-- Se suman al costeo de la cotización en /precios.
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.fabricacion_articulos_externos (
  id bigint generated by default as identity primary key,
  fabricacion_id bigint not null references public.fabricaciones(id) on delete cascade,
  descripcion text not null,
  cantidad numeric not null default 1,
  valor_unitario numeric not null default 0,
  usuario_email text,
  created_at timestamptz not null default now()
);

create index if not exists fabricacion_articulos_externos_fab_idx on public.fabricacion_articulos_externos (fabricacion_id);

alter table public.fabricacion_articulos_externos enable row level security;

drop policy if exists "fabricacion_articulos_externos_admin_all" on public.fabricacion_articulos_externos;
create policy "fabricacion_articulos_externos_admin_all" on public.fabricacion_articulos_externos
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());
