-- ============================================================
-- 0021_caja_herramientas.sql
-- Herramientas sueltas dentro de cada caja de acopio (lista libre
-- por caja: nombre de herramienta + cantidad). El admin carga las
-- herramientas de cada caja; el encargado solo las ve.
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.caja_herramientas (
  id bigint generated by default as identity primary key,
  caja_id bigint not null references public.insumos(id) on delete cascade,
  herramienta text not null,
  cantidad numeric not null default 1,
  unidad text not null default 'unid',
  created_at timestamptz not null default now()
);

create index if not exists caja_herramientas_caja_id_idx on public.caja_herramientas (caja_id);

alter table public.caja_herramientas enable row level security;

drop policy if exists "caja_herramientas_select_authenticated" on public.caja_herramientas;
create policy "caja_herramientas_select_authenticated" on public.caja_herramientas
  for select to authenticated using (true);

drop policy if exists "caja_herramientas_admin_write" on public.caja_herramientas;
create policy "caja_herramientas_admin_write" on public.caja_herramientas
  for all to authenticated
  using (public.es_admin())
  with check (public.es_admin());
