-- 0023_cargar_cajas.sql
-- Carga inicial de herramientas en las 3 cajas de Gral. Villegas
-- Ejecutar en Supabase SQL Editor

delete from public.caja_herramientas where caja_id in (select id from public.insumos where deposito = 'Gral. Villegas' and nombre like 'Caja de herramientas%');

with cajas as (select id, nombre from public.insumos where deposito = 'Gral. Villegas')
insert into public.caja_herramientas (caja_id, herramienta, cantidad) select c.id, v.herramienta, v.cantidad from cajas c join (values
  ('Caja de herramientas 1 - Gral. Villegas', 'Francesa 18 pulg', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Pico loro', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Corta Hierro', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Maza 1,5kg', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Barreta', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'llave 15/16', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'llave 7/8', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'llave 1 1/8', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'llave 3/4', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Pinza perro', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Martillo bolita', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Pinza Universal', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Pistola Silicona', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Destornillador philip', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Destornillador Plano', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Cutter', 1),
  ('Caja de herramientas 1 - Gral. Villegas', 'Llave 1/2', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Llave 10', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Llave 7/16', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Llave 5/8', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Llave 11/16', 2),
  ('Caja de herramientas 1 - Gral. Villegas', 'Llave para macho', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Martillo Bolita', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Corta hierro', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Pinza perro', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Francesa 18 pulgadas', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Maza 1,5 Kg', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 1 1/8', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 15/16', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 7/8', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 3/4', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Pico loro', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Pistola silicona', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Barretin', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Destornillador Philip', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Destornillador plano', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Cutter', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Pinza universal', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Allem Milimetrica', 1),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 11/16', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 5/8', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 9/16', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 1/2', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 7/16', 2),
  ('Caja de herramientas 2 - Gral. Villegas', 'Llave 10', 2),
  ('Caja de herramientas 3 - Gral. Villegas', 'Juego tubo', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Criket juego tubo', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Aparejo 2T', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Maquina de Soldar', 2),
  ('Caja de herramientas 3 - Gral. Villegas', 'Taladro percutor', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Pistola de impacto', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Amoladora 9 Pulg', 2),
  ('Caja de herramientas 3 - Gral. Villegas', 'Llave Stilson 2 Pulg', 2),
  ('Caja de herramientas 3 - Gral. Villegas', 'Amoladora 4 Pulg', 2),
  ('Caja de herramientas 3 - Gral. Villegas', 'Mochila fumigadora', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Faja 2Mtrs x 2 T', 2),
  ('Caja de herramientas 3 - Gral. Villegas', 'Faja 1 Mtrs x 2 T', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Soga', 1),
  ('Caja de herramientas 3 - Gral. Villegas', 'Grillete', 3)
) as v(caja_nombre, herramienta, cantidad) on v.caja_nombre = c.nombre;