-- ============================================================
-- 0025_control_herramientas_log.sql
-- Registro de controles de herramientas por caja. Cada vez que
-- se hace un conteo físico se guarda qué había en sistema, qué
-- se contó y la diferencia, con usuario y fecha.
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.caja_control_log (
  id bigint generated by default as identity primary key,
  caja_id bigint not null references public.insumos(id) on delete cascade,
  herramienta_id bigint references public.caja_herramientas(id) on delete set null,
  herramienta text not null,
  cantidad_sistema numeric not null,
  cantidad_contada numeric not null,
  diferencia numeric not null,
  usuario_email text,
  created_at timestamptz not null default now()
);

create index if not exists caja_control_log_caja_id_idx on public.caja_control_log (caja_id);
create index if not exists caja_control_log_created_at_idx on public.caja_control_log (created_at desc);

alter table public.caja_control_log enable row level security;

drop policy if exists "caja_control_log_select_authenticated" on public.caja_control_log;
create policy "caja_control_log_select_authenticated" on public.caja_control_log
  for select to authenticated using (true);

drop policy if exists "caja_control_log_insert_admin_encargado" on public.caja_control_log;
create policy "caja_control_log_insert_admin_encargado" on public.caja_control_log
  for insert to authenticated
  with check (public.es_admin() or exists (select 1 from public.perfiles where id = auth.uid() and rol = 'encargado'));
