-- ============================================================
-- 0032_remitos.sql
-- Remitos de entrega: cabecera (cliente, destino, transporte,
-- chofer, observaciones) + ítems libres, con numeración única
-- automática (R-0001, R-0002...). Solo lectura/escritura para
-- administración (admin y subadmin, vía es_gestion()).
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.remitos (
  id bigint generated by default as identity primary key,
  numero bigint,
  fecha timestamptz not null default now(),
  cliente text,
  destino text,
  transporte text,
  chofer text,
  observaciones text,
  usuario_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.remito_items (
  id bigint generated by default as identity primary key,
  remito_id bigint not null references public.remitos(id) on delete cascade,
  descripcion text not null,
  cantidad numeric not null default 1,
  unidad text not null default 'unid'
);

create index if not exists remito_items_remito_idx on public.remito_items (remito_id);

create sequence if not exists public.remitos_numero_seq;

create or replace function public.asignar_numero_remito()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if NEW.numero is null then
    NEW.numero := nextval('public.remitos_numero_seq');
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_remitos_numero on public.remitos;
create trigger trg_remitos_numero before insert on public.remitos
  for each row execute function public.asignar_numero_remito();

create unique index if not exists remitos_numero_uniq_idx on public.remitos (numero);

alter table public.remitos enable row level security;
alter table public.remito_items enable row level security;

drop policy if exists "remitos_gestion_all" on public.remitos;
create policy "remitos_gestion_all" on public.remitos
  for all to authenticated
  using (public.es_gestion())
  with check (public.es_gestion());

drop policy if exists "remito_items_gestion_all" on public.remito_items;
create policy "remito_items_gestion_all" on public.remito_items
  for all to authenticated
  using (public.es_gestion())
  with check (public.es_gestion());
