-- ============================================================
-- 0033_ordenes_compra.sql
-- Órdenes de compra a proveedores: cabecera (proveedor, estado,
-- observaciones) + ítems libres (pueden vincularse a un insumo
-- del stock). Numeración única automática (OC-0001...).
-- Estados: pendiente -> aprobada -> recibida (o cancelada).
-- Al marcar como recibida, la app suma al stock los ítems
-- vinculados a insumos usando registrar_movimiento_insumo.
--
-- Cómo aplicarlo: abrí Supabase → SQL Editor, pegá este archivo
-- completo y ejecutalo.
-- ============================================================

create table if not exists public.ordenes_compra (
  id bigint generated by default as identity primary key,
  numero bigint,
  fecha timestamptz not null default now(),
  proveedor text,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'aprobada', 'recibida', 'cancelada')),
  observaciones text,
  usuario_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.orden_compra_items (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes_compra(id) on delete cascade,
  insumo_id bigint references public.insumos(id) on delete set null,
  descripcion text not null,
  cantidad numeric not null default 1,
  unidad text not null default 'unid',
  precio_unitario numeric not null default 0
);

create index if not exists orden_compra_items_orden_idx on public.orden_compra_items (orden_id);

create sequence if not exists public.ordenes_compra_numero_seq;

create or replace function public.asignar_numero_oc()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if NEW.numero is null then
    NEW.numero := nextval('public.ordenes_compra_numero_seq');
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_ordenes_compra_numero on public.ordenes_compra;
create trigger trg_ordenes_compra_numero before insert on public.ordenes_compra
  for each row execute function public.asignar_numero_oc();

create unique index if not exists ordenes_compra_numero_uniq_idx on public.ordenes_compra (numero);

alter table public.ordenes_compra enable row level security;
alter table public.orden_compra_items enable row level security;

drop policy if exists "ordenes_compra_gestion_all" on public.ordenes_compra;
create policy "ordenes_compra_gestion_all" on public.ordenes_compra
  for all to authenticated
  using (public.es_gestion())
  with check (public.es_gestion());

drop policy if exists "orden_compra_items_gestion_all" on public.orden_compra_items;
create policy "orden_compra_items_gestion_all" on public.orden_compra_items
  for all to authenticated
  using (public.es_gestion())
  with check (public.es_gestion());
